baseURL: "https://flourishing-malasada-fc6748.netlify.app/"
languageCode: "zh-TW"
title: "許原碩"
theme: "PaperMod"

params:
    homeInfoParams:
        Title: Hello 我是許原碩 👋
        Content: This is a sample hugo template

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/Ken-Hsu66"
        - name: "twitter"
          url: "https://twitter.com/Yuanshuo99"
    ShowReadingTime: true
    author: "HsuKen"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: search
          name: Search
          url: /search/
          weight: 20
        - identifier: archive
          name: Archive
          url: /archives/
          weight: 20