baseURL: "https://hsuken.netlify.app/"
languageCode: "zh-TW"
title: "HsuKen"
theme: "Logseq Schrödinger"

params:
    homeInfoParams:
        Title: Hey there 👋
        Content: Feel free to look around.

    socialIcons: # optional
        - name: "twitter"
          url: "https://twitter.com/Yuanshuo99"
        - name: "instagram"
          url: "https://www.instagram.com/ken1029_/"
        - name: "github"
          url: "https://github.com/Ken-Hsu66"
    ShowReadingTime: true
    author: "HsuKen"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: search
          name: Search
          url: /search/
          weight: 20
        - identifier: archive
          name: Archive
          url: /archives/
          weight: 20